### PR TITLE
Create ohohoh456_HelloWorld

### PR DESCRIPTION
**Pull request by ohohoh456**
Hello world for hacktoberfest2023 pls add hacktoberfest accepted label

### CODE REVIEW

**Comment by ridholess** [comment]
@ohohoh456 what type of programming language is it?

**Comment by ohohoh456** [comment]
its python code

**Comment by ohohoh456** [comment]
@newridho could you maybe merge this by today? I really need it for a full completion of Hacktoberfest

**Comment by ridholess** [comment]
Okay, I'll change the name later

**Comment by ohohoh456** [comment]
Thank you so much!

**Pull request merged**
